version: '3.9'
services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: attendance
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - '127.0.0.1:5432:5432'

  api:
    build: ./backend
    restart: always
    environment:
      DATABASE_URL: postgres://postgres:postgres@db:5432/attendance
      AZURE_CLIENT_ID: change_me
      AZURE_CLIENT_SECRET: change_me
      AZURE_TENANT_ID: change_me
      ADMIN_EMAILS: admin@example.com
    depends_on:
      - db
    volumes:
      - ./backend:/usr/src/app
    ports:
      - '3000:3000'

  frontend:
    image: nginx:alpine
    volumes:
      - ./frontend/public:/usr/share/nginx/html
      - ./frontend/docker/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - '8080:80'
    depends_on:
      - api

volumes:
  db-data:
